theme: jekyll-theme-minimal
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
title: Caccio's BLOG
description: Recupero dei contenuti pi√π recenti del mio blog!
author: Stefano Cazzella
